### ISSUE TITLE
Strings: Provide default strings or lokalise credentials

### ISSUE THREAD

**Issue by jeffnyauke** [HedvigInsurance/android#2097]
Unable to get the project up and running because no access to lokalise strings

**Comment by StylianosGakis** [comment]
Hey Jeff, even if you did get access to strings, or even if you put empty strings for everything, you would still not really be able to run the project as it also depends on some internal libraries that are not possible to be used by someone outside of the company.
This is not something I think we are going to change anytime soon unfortunately.
Having the code able to be compiled by anyone isn't really a goal that we have.

If you *really* want to run this and want to put some effort into doing it, you would have to create empty strings for all the identifiers we have in the app, and put them inside [core-resources](https://github.com/HedvigInsurance/android/tree/develop/app/core/core-resources), and then you'd have to find the dependency which is not public, remove it, and go in the relative module and remove that code which references that library and replace it with a no-op perhaps.

In any case, it's a lot of effort which I don't expect anyone to do, and there wouldn't be a lot to earn from doing so anyway.

I would like to hear what your goal was when trying to run this project btw, maybe I can help you in some other way here? 👀

**Comment by jeffnyauke** [comment]
Hi Stylianos

Thanks for clarifying the limitations of running the project externally. 

The reason I was trying to run the project was to create an account and have a full experience of the app.  Unfortunately, since the app seems to have location restrictions, I'm unable to do that even after downloading it from the Play Store. 

Without going past the login screen, I am unable to have a clear picture of what I am seeing in the codebase. Is there any documentation available that outlines the functionalities of the app?  That might be helpful for my purposes.

Thanks again for your explanation and willingness to help!

**Comment by StylianosGakis** [comment]
Try long pressing the QR code when it shows up when trying to log in. This will allow you to enter "Demo mode", which is a limited view of how the app looks like and is built precisely for this reason, getting to see inside the app without having a real account.
